project:
  type: website

website:
  title: "KB"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Portfolio"
        menu:
          - href: portfolio/rl_crane.qmd
            text: "RL Quay Crane"
          - href: portfolio/integration_layer.qmd
            text: "Operational Integration Layer"
          - href: portfolio/digital_twin.qmd
            text: "Terminal Digital Twin"
          - href: portfolio/discharge_prediction.qmd
            text: "Predicted Container Discharge Time"
          - href: portfolio/point_in_time.qmd
            text: "Point-in-Time Data Reconstruction"
        

format:
  html:
    theme: lux
    css: styles.css
    # fontsize: 1.1em
    # code-fold: true       # Hides code behind a toggle
    # toc: true             # Floating table of contents
    # toc-location: left
    # number-sections: true
    # reference-location: margin  # Places citations in the margin (DeepMind style)
    # citation-location: margin